// gerado/src/main/webapp/app/pages/signup/signup.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'signup',
  template: `<mat-card ></mat-card>
   
   <form>
   <External Component id="mat-card-header" value={{ this.state.mat-card-header }} />
		<External Component id="mat-card-title" value={{ this.state.mat-card-title }} />
		<External Component id="mat-input" value={{ this.state.mat-input }} />
		<External Component id="mat-form-field" value={{ this.state.mat-form-field }} />
		<External Component id="mat-hint" value={{ this.state.mat-hint }} />
		<External Component id="mat-hint" value={{ this.state.mat-hint }} />
		<External Component id="mat-form-field" value={{ this.state.mat-form-field }} />
		<External Component id="mat-input" value={{ this.state.mat-input }} />
		<External Component id="mat-hint" value={{ this.state.mat-hint }} />
		
	
	
	<button (click)="onSubmit">onSubmit</button>
	
	</form>`
})
export class signup implements OnInit
{constructor() { }

  ngOnInit(): void 
  {
  }
	onSubmit() : void 
	{
		//TODO To be implemented
	}
    
}

// gerado/src/main/webapp/app/pages/signup/signup.jsx
import React from 'react';
import ReactDOM from 'react-dom';

export default function signup(props) {

	
	onSubmit() 
	{
		//TODO To be implemented
	}
	
	
	render() {  
      return (
        <div><mat-card ></mat-card>
   
   <form>
   <External Component id="mat-card-header" value={{ this.state.mat-card-header }} />
		<External Component id="mat-card-title" value={{ this.state.mat-card-title }} />
		<External Component id="mat-input" value={{ this.state.mat-input }} />
		<External Component id="mat-form-field" value={{ this.state.mat-form-field }} />
		<External Component id="mat-hint" value={{ this.state.mat-hint }} />
		<External Component id="mat-hint" value={{ this.state.mat-hint }} />
		<External Component id="mat-form-field" value={{ this.state.mat-form-field }} />
		<External Component id="mat-input" value={{ this.state.mat-input }} />
		<External Component id="mat-hint" value={{ this.state.mat-hint }} />
		
	
	
	<button onClick="onSubmit">onSubmit</button>
	
	</form></div>
      );
    }
  }

}
