// gerado/src/main/webapp/app/components/header/header.jsx
import React from 'react';
import ReactDOM from 'react-dom';

export default function header(props) {

	
	thankYou() 
	{
		//TODO To be implemented
	}
	
	
	render() {  
      return (
        <div><header ></header><mat-toolbar ></mat-toolbar><mat-icon ></mat-icon>
	
	<button onClick="thankYou">thankYou</button>
	
	</div>
      );
    }
  }

}

// gerado/src/main/webapp/app/components/header/header.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'header',
  template: `<header ></header><mat-toolbar ></mat-toolbar><mat-icon ></mat-icon>
	
	<button (click)="thankYou">thankYou</button>
	
	`
})
export class header implements OnInit
{constructor() { }

  ngOnInit(): void 
  {
  }
	thankYou() : void 
	{
		//TODO To be implemented
	}
    
}
