// gerado/src/main/webapp/app/pages/home/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'home',
  template: `<mat-card ></mat-card><mat-card-header ></mat-card-header><mat-card-content ></mat-card-content><mat-card-title ></mat-card-title>`
})
export class home implements OnInit
{constructor() { }

  ngOnInit(): void 
  {
  }
}

// gerado/src/main/webapp/app/pages/home/home.jsx
import React from 'react';
import ReactDOM from 'react-dom';

export default function home(props) {

	
	
	render() {  
      return (
        <div><mat-card ></mat-card><mat-card-header ></mat-card-header><mat-card-content ></mat-card-content><mat-card-title ></mat-card-title></div>
      );
    }
  }

}
